AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 120
  IgnoredPatterns: ['\A#', '\A\s*#']

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'it', 'let', 'before']

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 30

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: false